version: "3"
services:
  tomcat:
    container_name: tomcat
    image: tomcat
    ports:
      - '8080:8080'
    volumes:
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      # The configuration below is only for verification.
      - ./tomcat/manager.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml 
    networks:
      - concrete

  jenkins:
    restart: always
    container_name: jenkins_challenge
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"  
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked  
    ports:
      - '82:8080'
      - '50000:50000'
    image: jenkins_challenge:v1
    networks:
      - concrete
    volumes:
      - jenkins_log:/var/log/jenkins
      - jenkins_data:/var/jenkins_home

networks:
  concrete:
    driver: bridge

volumes:
  jenkins_data:
    driver: local
  jenkins_log:
    driver: local